### ISSUE TITLE
soname policy

### ISSUE THREAD

**Issue by sergey-239** [CauldronDevelopmentLLC/cbang#103]
Joseph,
I remember that you have no versioning policy in general.
However, in the review response [0] reviewer points that it probably good to have your decision on `soname` and its versioning. I replied:
```
As 1) Joseph adds the functionality on as needed basis, 2) there
are obvious bugfixes, 3) camotics builds properly with up-to-date version of cbang
and 4) cbang exports c++ classes, I decided to use `version.subversion` as an so version,
leaving `.revision` for bug fixes in cbang. The leading zero in `libcbang0` is from 
upstream, I suspect that it is somehow related to debian packaging/naming, so I 
leaved this as is. 
```
So, the idea is to have versioned so name up to subversion number, i.e. `libcbang0.so.1.7` presently, to allow bug fixes updates of shared `cbang` library without the need to rebuild camotics. 

Do you have any objections or another vision?

Thank you,
Sergey

[0] https://bugzilla.redhat.com/show_bug.cgi?id=2129303#c2

**Comment by jcoffland** [comment]
No objections.  Thank you!
