### ISSUE TITLE
RSA_SSLV23_PADDING issue with cbang tag 1.3.1

### ISSUE THREAD

**Issue by hpmachining** [CauldronDevelopmentLLC/cbang#116]
I am trying to maintain the Camotics 1.2.0 release on the arch linux aur, which requires me to use the cbang tag 1.3.1 to build. I am getting an error trying to build this tag, which I think is because of openssl 3 instead of 2. Here is the error:

```
src/cbang/openssl/KeyContext.cpp: In member function ‘void cb::KeyContext::setRSAPadding(padding_t)’:
src/cbang/openssl/KeyContext.cpp:94:34: error: ‘RSA_SSLV23_PADDING’ was not declared in this scope; did you mean ‘SSLV23_PADDING’?
   94 |   case SSLV23_PADDING: padding = RSA_SSLV23_PADDING; break;
      |                                  ^~~~~~~~~~~~~~~~~~
      |                                  SSLV23_PADDING
src/cbang/openssl/KeyContext.cpp: In member function ‘void cb::KeyContext::setRSAPubExp(uint64_t)’:
src/cbang/openssl/KeyContext.cpp:121:41: warning: ‘int EVP_PKEY_CTX_set_rsa_keygen_pubexp(EVP_PKEY_CTX*, BIGNUM*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  121 |   if (EVP_PKEY_CTX_set_rsa_keygen_pubexp(ctx, num) <= 0) {
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
In file included from src/cbang/openssl/KeyContext.cpp:42:
/usr/include/openssl/rsa.h:131:5: note: declared here
  131 | int EVP_PKEY_CTX_set_rsa_keygen_pubexp(EVP_PKEY_CTX *ctx, BIGNUM *pubexp);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scons: *** [build/cbang/openssl/KeyContext.o] Error 1
scons: building terminated because of errors.
```

Is this something you can help me with? If Camotics 1.2.0 doesn't need it and there is a way to build cbang without the RSA  keygen features, that would probably work.

**EDIT:** I can get it to build if I change `RSA_SSLV23_PADDING` to `SSLV23_PADDING` and add `-fpermissive` to the cxxflags (for a different error), but then one of the tests fails. I don't know what all the ramifications of these changes are. Here is the failed test error:

```
BlowfishTest: stdout stderr return                                      [FAILED]
```

**EDIT 2:** I succesfully built with ``cxxflags="-fpermissive" with_openssl=false``, but I can't figure out how to get the tests to skip the openssl related tests. I tried running scons in the tests directory with ``with_openssl=false`` and also ``openssl=false``

**Comment by jcoffland** [comment]
CAMotics does use hashing functions from OpenSSL and older cbang does not support OpenSSL 3.0.  I recommend upgrading CAMotics and cbang to the latest versions. I'm close to making a new CAMotics release.  I recommend using CAMotics tag ``v1.3.0`` with cbang ``1.8.0``.  If you have any trouble with these versions let me know and I'll try to fix any problems quickly.

**Comment by jcoffland** [comment]
Closing this, as 1.3.1 does not support OpenSSL 3.0.

**Comment by hpmachining** [comment]
I'm having an issue with latest V8 and runtime issues in CAMotics. Do you want me to open an issue here or in CAMotics repository?

**Comment by jcoffland** [comment]
Sounds like it could be two issues.  If it's specific to CAMotics then open it there.  Otherwise, here.  Thanks.

**Comment by hpmachining** [comment]
It is the cbang build that I ended up patching to get CAMotics to build and run correctly, so I'll post the details in cbang. Thank you.
