### ISSUE TITLE
Option --respawn fails to unset option log

### ISSUE THREAD

**Issue by kbernhagen** [CauldronDevelopmentLLC/cbang#13]
On macOS 10.9+, fahclient is started with --respawn alone, which results in client logs being overwritten by log rotation by the child process. The rotated logs have timestamp in seconds, but respawn takes much less time than that. Result is a rotated logs directory which is mostly uninteresting parent process logs. (Parent rotates previous client log and starts child. Child rotates parent log overwriting previous log.)

Respawn should unset log, just as daemon does.

Need a simple option action ServerApplication::respawnAction, something like
```
if (!options["child"].toBoolean()
  && options["respawn"].toBoolean())
    options["log"].unset();
```

**Comment by jcoffland** [comment]
Thanks.
