### ISSUE TITLE
Use SPDX license identifier

### ISSUE THREAD

**Issue by marcosfrm** [CauldronDevelopmentLLC/cbang#136]
For consistency with:

https://github.com/FoldingAtHome/fah-client-bastet/commit/7b67fc24eebc747ac2522e0d70e84f3786ba2eba

https://github.com/CauldronDevelopmentLLC/cbang/blob/305c01cbb7efded46421f4cc7f57b523c300767a/SConstruct#L39

https://github.com/CauldronDevelopmentLLC/cbang/blob/305c01cbb7efded46421f4cc7f57b523c300767a/debian/copyright#L8

**Comment by kbernhagen** [comment]
LGPL-2.1

**Comment by kbernhagen** [comment]
The LICENSE file also needs updating.

**Comment by jcoffland** [comment]
The ``LICENSE`` file is the license itself.  It shouldn't be modified.  The ``+`` means that license or any newer version at the user's discretion which is explained in each of the code tags.

**Comment by marcosfrm** [comment]
The SPDX license identifier for LGPL-2.1+ is `LGPL-2.1-or-later`:

https://spdx.org/licenses/LGPL-2.1-or-later.html

**Comment by jcoffland** [comment]
Indeed LGPL-2.1+ is in the list of deprecated SPDX license identifiers.
