### ISSUE TITLE
Python platform.dist() is buggy

### ISSUE THREAD

**Issue by marcosfrm** [CauldronDevelopmentLLC/cbang#150]
https://github.com/CauldronDevelopmentLLC/cbang/blob/aaefdf524cfbc05320c3c16437d3593a106b8333/config/packager/__init__.py#L43

It was removed in Python 3.8. With Python 3.6 from openSUSE Leap 15.5:

```
Python 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> hasattr(platform, 'dist')
True
>>> print(platform.dist())
('', '', '')
>>> 
```

Too many bugs: https://bugs.python.org/issue28167

**Comment by kbernhagen** [comment]
Is the recommended replacement [distro](https://pypi.org/project/distro/)?

**Comment by marcosfrm** [comment]
Yes, but `/etc/os-release` is already parsed in `get_dist()`. Maybe `platform.dist()` was useful before `/etc/os-release` standardization. Any non-ancient Linux distribution has `/etc/os-release` now.

**Comment by marcosfrm** [comment]
@jcoffland Can we simply remove `platform.dist()` usage?

**Comment by jcoffland** [comment]
done
