### ISSUE TITLE
Tried Building Cbang on WIndows 11 Failed with errors

### ISSUE THREAD

**Issue by Duken30** [CauldronDevelopmentLLC/cbang#153]
The following is the errors I got. This is over my head to look through and troubleshoot is there a maintainer that could help me with this? I am attempting to build the Folding at Home F@H Screensaver and CBang is a prerequisite for this.

src\cbang\api\API.cpp(165): error C2872: 'API': ambiguous symbol
src\cbang/api/handler/CORSHandler.h(45): note: could be 'cb::API'
C:\Git\cbang\src\cbang\api\API.h(48): note: or       'cb::API::API'
src\cbang\api\API.cpp(226): error C2872: 'API': ambiguous symbolscons: *** [src\cbang\api\handler\ArgFilterProcess.obj] Error 2

src\cbang/api/handler/CORSHandler.h(45): note: could be 'cb::API'
C:\Git\cbang\src\cbang\api\API.h(48): note: or       'cb::API::API'
src\cbang\api\API.cpp(247): error C2872: 'API': ambiguous symbol
src\cbang/api/handler/CORSHandler.h(45): note: could be 'cb::API'
C:\Git\cbang\src\cbang\api\API.h(48): note: or       'cb::API::API'
src\cbang\api\API.cpp(253): error C2872: 'API': ambiguous symbol
src\cbang/api/handler/CORSHandler.h(45): note: could be 'cb::API'
C:\Git\cbang\src\cbang\api\API.h(48): note: or       'cb::API::API'
scons: *** [src\cbang\api\API.obj] Error 2
scons: building terminated because of errors.

**Comment by jcoffland** [comment]
This builds fine with gcc 13.  I've committed a change for compilers for which this is ambiguous.
