### ISSUE TITLE
Please include copyright information in source files

### ISSUE THREAD

**Issue by petterreinholdtsen** [CauldronDevelopmentLLC/cbang#162]
When running 'debmake -cc' on the source, it report several files are missing copyright information, for example config/XML/__init__.py and scripts/update_boost.sh. It would be easier to keep a machine generated debian/copyright if each individual file have copyright information.

**Comment by jcoffland** [comment]
https://github.com/CauldronDevelopmentLLC/cbang/blob/master/config/XML/__init__.py does have a copyright notice.  Looks like it was added 10 months ago.

**Comment by jcoffland** [comment]
Added copyright and license to ``scripts/update_boost.sh``.

**Comment by jcoffland** [comment]
Ok.  I ran ``debmake -cc`` and this is what I found:

I've added copyright tags to the following:

           SConstruct
           SConscript
           docs/www/Makefile
           docs/www/css/style.css
           docs/www/index.jade
           docs/www/js/main.js
           .travis.yml

These seem not applicable:

           .gitignore
           README.md
           cbang.png
           docs/www/images/cbang.ico
           docs/www/images/cbang.png
           src/resources/licenses/sqlite3.txt
           debian/*
           patches/*

These are 3rd party libs which should not be included in the Debian build.  Note, ``libevent`` is an exception because I've modified ``libevent`` from its original source.

           src/ZLib/*
           src/boost/*
           src/expat/*
           src/libyaml/*
           src/re2/*
           src/sqlite3/*
           src/libevent/*

All the non-source files in ``tests`` cannot have copyrights as it would break the test system.

           tests/*

I assume there is some way to tell Debian to ignore certain files with respect to copyright.

**Comment by petterreinholdtsen** [comment]
[Joseph Coffland]
> Ok.  I ran ``debmake -cc`` and this is what I found:

Very good. :)

> These are 3rd party libs which should not be included in the Debian
> build.

Probably easiest to just exclude these from the Debian orig tarball.

> Note, ``libevent`` is an exception because I&#39;ve modified
> ``libevent`` from its original source.

Aha.  Then I guess you should either submit the patches upstream to get
it into the upstream project, or change the name of your edition to make
it obvious that they are not the same.

> I assume there is some way to tell Debian to ignore certain files with
> respect to copyright.

The two approaches is to state the copyright in a d/copyright without
specified license in the file, or (if the license must be assumed to be
non-free or the file is unwanted in the Debian source - like .o or .dll
files) exclude it from the Debian orig tarball.  The latter is easiest
to handle by listing entries under Files-Excluded: in d/copyright and
using uscan to fetch the upstream tarball.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by jcoffland** [comment]
I've submitted some very simple patches to ``libevent`` they were accepted after about 8 years.  My changes in cbang are much more extensive.  I suppose I could just rename the directory and add a note that it is new code based on ``libevent``.
