### ISSUE TITLE
Websocket support has hard dependency on OpenSSL, ignores with_openssl=no

### ISSUE THREAD

**Issue by str4d** [CauldronDevelopmentLLC/cbang#44]
https://github.com/CauldronDevelopmentLLC/cbang/blob/8ea71681a5c51d44579cf9db8e8356f88fac4fca/src/cbang/event/Websocket.cpp#L38

As a workaround, websocket support can be disabled with `scons disable_local=libevent`, which causes the entire `event` submodule to be disabled.

**Comment by jcoffland** [comment]
You should probably continue to use ``disable_local=libevent`` but I fixed this error.
