### ISSUE TITLE
Use C++ versions of headers

### ISSUE THREAD

**Issue by peastman** [CauldronDevelopmentLLC/cbang#50]
C++ code should import the versions of headers that put everything in the std namespace, for example `<cstdio>` instead of `<stdio.h>`.  Lots of code in cbang imports the C version instead.  For example,

https://github.com/CauldronDevelopmentLLC/cbang/blob/2fb0be7809c5e45287a122ca5fbc15b5ae859a3b/src/cbang/String.cpp#L41-L45

See https://github.com/FoldingAtHome/openmm-core/issues/212.

**Comment by jcoffland** [comment]
I'll look in to this.  It might be a big job.  I usually just use ``::`` to globally scope class where necessary.  I can be difficult to guarantee that no C system headers get included when you relay on 3rd-party C libraries.  However, I do try to keep 3rd-party includes out of .h files in cbang.

**Comment by jcoffland** [comment]
This is complete.
