### ISSUE TITLE
Use seekable streams for cb::SystemUtilities::iopen and oopen

### ISSUE THREAD

**Issue by jchodera** [CauldronDevelopmentLLC/cbang#57]
`cbang` [`iopen`](https://github.com/CauldronDevelopmentLLC/cbang/blob/9e792bced9912c861683bacb4fe7b1ffd65ebd32/src/cbang/os/SystemUtilities.cpp#L1049-L1082) and [`oopen`](https://github.com/CauldronDevelopmentLLC/cbang/blob/9e792bced9912c861683bacb4fe7b1ffd65ebd32/src/cbang/os/SystemUtilities.cpp#L1085-L1122) currently opens input/output files without`ios::binary` mode for gzip and bzip2, causing the read file contents to contain extra `\r` characters due to text mode in 

Instead, the files should be opened with `| ios::binary` when reading/writing in bzip2 and gzip formats.

**Comment by jchodera** [comment]
We should also probably support the same sets of extensions you use [here](https://github.com/CauldronDevelopmentLLC/cbang/blob/4d9e6cf4ae97f46b9bd9c59c32a4dfae709bf7bd/src/cbang/tar/TarFile.cpp#L41-L49): `.bz2` and `.bzip2`, as well as `.gz` and `.gzip`.

**Comment by jcoffland** [comment]
Files are always opened with ``ios::binary`` in cbang.  If you don't use this flag on Windows, Windows will strip out ``\r`` automatically.  This causes serious problems when reading binary files.

**Comment by jchodera** [comment]
I'm still confused then---is there a way to avoid having this function randomly _insert_ `\r` on `linux` then?

**Comment by jcoffland** [comment]
Linux never inserts or strips ``\r``.  I'm guessing the ``\r``s are already in the file.  You can use a tool like ``hexdump -C`` to check this.

**Comment by jchodera** [comment]
They don't appear to be:
```
hexdump -c system.xml.bz2  | grep "\r"
```
shows nothing. Reading the uncompressed XML file works fine. Reading the compressed XML file (compressed with either `gzip` or `bzip2`) shows the correct text when printed to the log, but the XML parser fails. Stripping `\r` causes the XML reader to work.

What you're suggesting is (1) both `gzip` and `bzip2` will silently add `\r`, and (2) these characters are invisible to `hexdump`, which does not seem to make sense. I think there's something yet we don't quite understand here.

Here's an example of these files compressed and uncompressed:
[examples.zip](https://github.com/CauldronDevelopmentLLC/cbang/files/4727152/examples.zip)

For more info: 
https://github.com/openmm/openmm/issues/2721#issuecomment-638520852

**Comment by jchodera** [comment]
An update here: It looks like the `\r` was a red herring, and instead the issue is that this code does not work for compressed files (but is fine for uncompressed files):
```C++
bool autoCompression = true;
System *sys = XmlSerializer::deserialize<System>
  (*cb::SystemUtilities::iopen(sysFile_, autoCompression));
```
whereas this seems to work for both:
```C++
  bool autoCompression = true;
  auto in = SystemUtilities::iopen(sysFile_, autoCompression);
  std::stringstream contents;
  cb::SystemUtilities::cp(*in, contents);
  std::string s(contents.str());
  contents.str(s);
  System *sys = XmlSerializer::deserialize<System>(contents);
```
Any ideas why?

**Comment by thtrummer** [comment]
You may have missed it in the other ticket but:
> Your problem here is that you provide a stream that is not seekable which results in the XML parser having no data to work with (at least when using compressed files).

**Comment by jchodera** [comment]
Whoops! 

For the compressed file, this returns `-1`, and for uncompressed, a positive number (the end of the stream?).

**Comment by thtrummer** [comment]
Yes and indirectly the size of the file. Your problem is that [XmlSerializer](https://github.com/openmm/openmm/blob/12f17a6ce9847e610a19228228abb1b153d775e9/serialization/src/XmlSerializer.cpp#L142) expects `tellg()`to return a useful value.

**Comment by jchodera** [comment]
It looks like the `ios::binary` issue was a red herring, and the actual root cause of the issues with OpenMM's `XmlSerializer` were indeed that the boost `iostream` and compression filters [are not seekable by default](https://stackoverflow.com/questions/34415054/seek-doesnt-work-on-stdistream-initialized-with-boost-filtering-istreambuf), though a [solution is presented](http://coliru.stacked-crooked.com/a/aff637be181a27da).

We should consider implementing a similar solution into `cbang`'s `iopen` and `oopen` to make the streams seekable.

**Comment by jcoffland** [comment]
Yeah, you cannot seek with compressed streams.  Why does XmlSerializer need to seek?  Is it just to find the size of the uncompressed data?  Knowing the size shouldn't be necessary for parsing XML.

**Comment by jchodera** [comment]
Closing this since we have a workaround:
```C++
  bool autoCompression = true;
  // Copy to a seekable stringstream
  std::stringstream contents;
  cb::SystemUtilities::cp(*SystemUtilities::iopen(sysFile_, autoCompression), contents);
  System* system = XmlSerializer::deserialize<System>(contents);
```
