### ISSUE TITLE
NameError: global name 'check_output' is not defined

### ISSUE THREAD

**Issue by dotsdl** [CauldronDevelopmentLLC/cbang#71]
When attempting to build `cbang` with:

```
scons -C cbang debug=1 -j2
```
I get:

```
  scons: Entering directory `/home/conda/workspace/cbang'
  scons: Reading SConscript files ...
     Compiler: gcc (gnu)
     Platform: posix
         Mode: gnu
         Arch: x86
  NameError: global name 'check_output' is not defined:
    File "/home/conda/workspace/cbang/SConstruct", line 34:
      conf.CBConfig('compiler')
    File "/usr/lib/scons/SCons/SConf.py", line 640:
      ret = self.test(context, *args, **kw)
    File "/home/conda/workspace/cbang/config/__init__.py", line 166:
      ret = conf.env.cb_methods[name](conf, **kwargs)
    File "/home/conda/workspace/cbang/config/compiler/__init__.py", line 189:
      if compiler == 'gnu': print('GCC Version:', gcc_version_str(env))
    File "/home/conda/workspace/cbang/config/compiler/__init__.py", line 19:
      return check_output(cmd).strip().decode('utf8')
```

Looking at `cbang/config/compiler/__init__.py`, [`check_output`](https://github.com/CauldronDevelopmentLLC/cbang/blob/ae2418e6d6783b2db45ae1983a109c7122fbd94b/config/compiler/__init__.py#L19) doesn't appear defined.

**Comment by dotsdl** [comment]
Is there a workaround for use of `gcc` in the meantime? Otherwise this is blocking use of `cbang` in the `openmm-core` build automation.

**Comment by jcoffland** [comment]
``check_output`` is in the Python ``subprocess`` module.  It was added in Python version 3.1.  What version of Python are you using?

**Comment by dotsdl** [comment]
Hmmm, bizarre! We get this problem [here](https://github.com/FoldingAtHome/openmm-core/runs/2153512232?check_suite_focus=true#step:7:366).

Really not sure how it can happen; digging back into it now. Apologies for the noise.

**Comment by jcoffland** [comment]
It looks like ``scons`` was installed before Python 3.6.  So it's probably using an older version, maybe even Python 2.

**Comment by dotsdl** [comment]
Indeed, went with installing `scons` as part of the conda env and the builds appear to be proceeding! Again, sorry to bark up the wrong tree here!

**Comment by jcoffland** [comment]
I have added a test to C! that checks that it has at least python v3.1 and gives a more meaningful error otherwise.
