### ISSUE TITLE
Do compression methods support multithreading?

### ISSUE THREAD

**Issue by jchodera** [CauldronDevelopmentLLC/cbang#76]
Does something need to be enabled to support multithreading with zlib/LZ4/bzip compression? Or are these inherently single- or multi-threaded?

**Comment by jcoffland** [comment]
No.  These compression algorithms are all single threaded.  I'm not aware of any multi-threaded implementations.

**Comment by jchodera** [comment]
The Folding@home slack folks point out that [7zip](https://www.7-zip.org/) is cross-platform, [multithreaded](https://www.7-zip.org/7z.html), and [licensed under LGPL](https://www.7-zip.org/faq.html#developer_faq). I haven't done any sort of a dive into how easy the core library is to integrate into cross-platform libraries, however.

**Comment by jcoffland** [comment]
I opened issue #79.
