### ISSUE TITLE
Sconstruct version string is inconsistent with published releases

### ISSUE THREAD

**Issue by sergey-239** [CauldronDevelopmentLLC/cbang#94]
Dear Joseph,
do you consider to tag the current HEAD with a new release as it looks like camotics 1.2.2 is going to be released soon?
Anyway, please update the version string in SCostruct.
Thank you!

**Comment by jcoffland** [comment]
I don't understand.  What do you want the version string to be?  It's already 1.2.2.

**Comment by sergey-239** [comment]
Joseph,

cbang/SConstruct:5:
version = '1.3.3'
The latest release tag is 1.6.1 and it is also quite outdated.

**Comment by jcoffland** [comment]
Sorry, I was confusing this with the CAMotics version.  I've tagged a new v1.7.0 cbang version.

**Comment by sergey-239** [comment]
Thank you!
