### ISSUE TITLE
Actual license

### ISSUE THREAD

**Issue by sergey-239** [CauldronDevelopmentLLC/cbang#96]
Joseph,
files COPYING and LICENSE are LGPLv2.1, while all files in src/cbang/ mention LGPLv2.1+ in its headers.

What is actual license of your code?

**Comment by sergey-239** [comment]
Joseph, 
the src/resources/licenses/cbang.txt also contains LGPLv2.1+. could you, please, synchronise this.

**Comment by jcoffland** [comment]
I think this is correct as it is.  There is no LGPLv2.1+ license.  LGPLv2.1+ means the LGPLv2.1 or at your option any newer version of the LGPL.  The files ``COPYING`` and ``LICENSE`` contain the actual license file.  The source file headers and ``src/resources/cbang.txt`` are references to the license.

I will remove the ``COPYING`` file.  I don't see why two such files are needed.

**Comment by jcoffland** [comment]
LGPLv2.1+ means LGPL version 2.1 or at your option any later version.  Are you still saying there's a problem?  I'm not seeing one.

**Comment by sergey-239** [comment]
Joseph,

I am sorry, I am wrong. I mistakenly thought that option to use later version should be in the text of license itself.
Regards,
Sergey.

**Comment by jcoffland** [comment]
No problem.
