### ISSUE TITLE
Versioning of cbang

### ISSUE THREAD

**Issue by sergey-239** [CauldronDevelopmentLLC/cbang#98]
Joseph,
as I am packaging the cbang as a shared library, I would like you to clarify your policy of cbang versioning so I could properly establish dependency of camotics on cbang library by means of `.so` version suffix: is the minor version number bumped only for bug fixes and the rest of version number for interface changes?
Thanks,
Sergey

**Comment by jcoffland** [comment]
The truth is that I don't have a proper versioning policy.  I've mainly bumped the version numbers when people using cbang have asked me to do so.  I make changes all the time based on the needs of the projects that use cbang (Folding@home, CAMotics, jmpapi, etc.).  Nearly, all of the commits to cbang are from me.

My policy is to keep the latest committed version of all the software that uses cbang up to date with the latest committed cbang.  I usually do not make breaking changes but if I do I update all the other projects at the same time.  So you should be able to rely on the latest versions working together.  If you want me to mark a version number you can always request it.

**Comment by sergey-239** [comment]
Thank you, I got.
